model = "gpt-5.2-codex"
model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true
web_search_request = true

notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]


[mcp_servers.aws-knowledge]
url = "https://knowledge-mcp.global.api.aws"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.figma]
url = "http://127.0.0.1:3845/mcp"

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp@latest"]
