[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo ='junegunn/vim-easy-align'
hook_add = 'source ~/.vim/scripts/plugins/vim-easy-align.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.vim/scripts/plugins/ale.vim'

[[plugins]]
repo = 'embear/vim-localvimrc'
