---
- hosts: localhost
  connection: local
  become: no

  tasks:

    - name: Check etc/shells
      shell: |
        cat /etc/shells | grep -p '\/usr\/local\/bin\/zsh'
      register: result
      ignore_errors: true

    - name: Add zsh to etc/shells
      shell: echo '/usr/local/bin/zsh' >> /etc/shells
      become: yes
      when: result|failed

    - debug: var=ansible_user_id

    - name: Change shell
      become: yes
      shell: chsh -s /usr/local/bin/zsh {{ ansible_user_id }}
