[tools]
go = "1.25"
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
pnpm = "10"
poetry = "2"
python = "3.14"
terraform = "1.14"
uv = "0.9"

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
