[tools]
go = "1.23"
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@openai/codex" = "latest"
pnpm = "10"
poetry = "2"
python = "3.13"
terraform = "1.11"
uv = "0.9"

[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
